version: '3'
services:
  api_promociones:
    build:
      context: ./api-promociones
      dockerfile: Dockerfile
    container_name: api-promociones-nodejs
    ports:
      - "8003:8003"
    volumes:
      - ./api-promociones:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo/promociones_db
    links:
      - mongo
  # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-community-with-docker/
  # mongosh --username admin --password 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./api-promociones/init.js:/docker-entrypoint-initdb.d/init.js
    logging:
      driver: none
  # command: bash -c 'sleep 30 && mongosh --username admin --password password < /docker-entrypoint-initdb.d/init.js'

  # api_clientes:
  #   build:
  #     context: ./api-clientes
  #     dockerfile: Dockerfile
  #   container_name: api-clientes-fastapi
  #   ports:
  #     - "8002:8002"
  #   volumes:
  #     - ./api-clientes:/app
  #   environment:
  #     - DB_USER=value
  #     - DB_PASSWORD=value
  #     - DB_HOST=value
  #     - DB_PORT=value
  #     - DB_NAME=value
  #     # - DB_URI=value

  # mysql_database:
  #   image: mysql:5.7
  #   container_name: mysql_database
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: clientes_db
  #   volumes:
  #     - ./api-clientes/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   logging:
  #     driver: none