version: '3'
services:
  api_promociones:
    build:
      context: ./api-promociones
      dockerfile: Dockerfile
    container_name: node-api
    ports:
      - "8003:8003"
    volumes:
      - ./api-promociones:/app
    environment:
      - MONGO_URI=mongodb://mongo/promociones_db
    links:
      - mongo
  # https://www.mongodb.com/docs/manual/tutorial/install-mongodb-community-with-docker/
  # mongosh --username admin --password 
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./api-promociones/init.js:/docker-entrypoint-initdb.d/init.js
    logging:
      driver: none
  # command: bash -c 'sleep 30 && mongosh --username admin --password password < /docker-entrypoint-initdb.d/init.js'
