openapi: 3.0.0
info:
  title: API Orquestador
  description: API para interactuar con los servicios de clientes, membresías y promociones.
  version: 1.0.0

servers:
  - url: "http://lb-prod-1093716168.us-east-1.elb.amazonaws.com:5000"

paths:
  /:
    get:
      summary: Verificar el estado de la API
      operationId: is_alive
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: API Orquestador is alive

  /api_clientes/:
    get:
      summary: Obtener datos de clientes
      operationId: api_clientes
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientes:
                    type: array
                    items:
                      type: object

  /api_membresias/:
    get:
      summary: Obtener datos de membresías
      operationId: api_membresias
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  membresias:
                    type: array
                    items:
                      type: object

  /api_promociones/:
    get:
      summary: Obtener datos de promociones
      operationId: api_promociones
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  promociones:
                    type: array
                    items:
                      type: object

  /verificar_membresia/{dni_cliente}:
    get:
      summary: Verificar estado de membresía
      operationId: verificar_membresia
      parameters:
        - name: dni_cliente
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
                  promociones:
                    type: array
                    items:
                      type: object
                  promociones_exclusivas:
                    type: array
                    items:
                      type: object
        "404":
          description: Cliente no encontrado
        "500":
          description: Error en la solicitud

  /cancelar_membresia:
    post:
      summary: Cancelar membresía
      operationId: cancelar_membresia
      parameters:
        - name: dni_cliente
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
        "500":
          description: Error en la solicitud

  /renovar_membresia:
    post:
      summary: Renovar membresía
      operationId: renovar_membresia
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                membresia:
                  type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
        "500":
          description: Error en la solicitud


# * UI (DNI) → Orquestador (POST /orquestador/verificar_membresia):

#     La UI envía el DNI para verificar la membresía del cliente.
#     El Orquestador verifica el cliente:
#         Orquestador → Microservicio de Clientes (GET /clientes/real/{dni})
#         Orquestador → Microservicio de Membresías (GET /membresias/{dni})
#     Respuesta del Orquestador:
#         Si la membresía está activa, responde a la UI con un mensaje de confirmación.
#         Si está caducada, la UI procede a solicitar las promociones.

# * UI (solicitud de promociones) → Orquestador (GET /orquestador/mostrar_promos):

#     La UI pide al Orquestador la lista de promociones disponibles.
#     El Orquestador hace una llamada a:
#         Orquestador → Microservicio de Promociones (GET /promociones)
#     El Orquestador devuelve a la UI la lista de promociones disponibles.

# * UI (selección de promoción) → Orquestador (POST /orquestador/renovar_membresia):

#     El cliente selecciona una promoción y la UI envía el DNI y el ID de la promoción al Orquestador.
#     El Orquestador valida la promoción y renueva la membresía:
#         Orquestador → Microservicio de Clientes (GET /clientes/{dni})
#         Orquestador → Microservicio de Membresías (GET /membresias/{dni})
#         Orquestador → Microservicio de Promociones (GET /promociones/{id})
#         Orquestador → Microservicio de Membresías (POST /membresias) (renovación de la membresía)
#     El Orquestador responde a la UI con la confirmación de la renovación exitosa.

# UI (DNI) -> Orquestador (POST /orquestador/cancelar_membresia)
#    La UI envia el DNI  para cancelar la membresia del cliente
#    Orquestador -> Coloca en estado inactivo al cliente (PUT /clientes/{dni})
#    Orquestador -> Actualiza la fecha de fin de la membresia (PUT /membresias/{dni})


# Flujo de la UI
#     El cliente ingresa su DNI y verifica su membresía.
#         Métodos invocados: POST /orquestador/verificar_membresia, GET /clientes/{dni}.

#     Si la membresía está caducada, se muestran las promociones generales y exclusivas por haber sido cliente activo.
#         Método invocado: GET /promociones.
#     Si el cliente es un invitado, se muestran las promociones generales y exclusivas por ser nuevo.
#         Método invocado: GET /promociones.

#     El cliente selecciona una promoción para renovar la membresía.
#         Métodos invocados: POST /orquestador/renovar_membresia, GET /promociones/{id}.

#     El cliente actualiza su información personal.
#         Método invocado: PUT /clientes/{dni}.

#    El cliente cancela su membresía.
#         Métodos invocados: POST /orquestador/cancelar_membresia, PUT /clientes/{dni}, PUT /membresias/{dni}.

