openapi: 3.0.0
info:
  title: API Orquestador
  description: API para interactuar con los servicios de clientes, membresías y promociones.
  version: "1.0.0"

servers:
  - url: "http://localhost:8000"

paths:
  /:
    get:
      summary: Verificar el estado de la API
      operationId: is_alive
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: API Orquestador is alive

  /api_clientes/:
    get:
      summary: Obtener datos de clientes
      operationId: api_clientes
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientes:
                    type: array
                    items:
                      type: object

  /api_membresias/:
    get:
      summary: Obtener datos de membresías
      operationId: api_membresias
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  membresias:
                    type: array
                    items:
                      type: object

  /api_promociones/:
    get:
      summary: Obtener datos de promociones
      operationId: api_promociones
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  promociones:
                    type: array
                    items:
                      type: object

  /verificar_membresia/{dni_cliente}:
    get:
      summary: Verificar estado de membresía
      operationId: verificar_membresia
      parameters:
        - name: dni_cliente
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
                  promociones:
                    type: array
                    items:
                      type: object
                  promociones_exclusivas:
                    type: array
                    items:
                      type: object
        "404":
          description: Cliente no encontrado
        "500":
          description: Error en la solicitud

  /cancelar_membresia:
    post:
      summary: Cancelar membresía
      operationId: cancelar_membresia
      parameters:
        - name: dni_cliente
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
        "500":
          description: Error en la solicitud

  /renovar_membresia:
    post:
      summary: Renovar membresía
      operationId: renovar_membresia
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cliente:
                  type: string
                membresia:
                  type: string
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "200"
                  message:
                    type: string
        "500":
          description: Error en la solicitud
