openapi: 3.0.0
info:
  title: API de Promociones
  description: API para gestionar las promociones disponibles.
  version: 1.0.0

servers:
  - url: http://localhost:8003
    description: Servidor de desarrollo

paths:
  /promociones:
    get:
      summary: Obtener todas las promociones
      responses:
        '200':
          description: Un arreglo JSON de promociones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    promocion_id:
                      type: integer
                    nombre:
                      type: string
                    descuento:
                      type: number
                    tipo_membresia:
                      type: string
    post:
      summary: Crear una nueva promoción
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                descuento:
                  type: number
                tipo_membresia:
                  type: string
      responses:
        '200':
          description: Promoción creada
