openapi: 3.0.0
info:
  title: API de Membresías
  description: API para gestionar las membresías del gimnasio.
  version: 1.0.0

servers:
  - url: http://localhost:8002
    description: Servidor de desarrollo

paths:
  /membresias/{dni}:
    parameters:
      - in: path
        name: dni
        required: true
        schema:
          type: string
    get:
      summary: Verificar membresía por DNI
      responses:
        '200':
          description: Detalles de la membresía
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  tipo:
                    type: string
                  fecha_inicio:
                    type: string
                  fecha_fin:
                    type: string
                  estado:
                    type: string
                  cliente_id:
                    type: integer
        '404':
          description: Membresía no encontrada
    post:
      summary: Crear o renovar una membresía
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                cliente_id:
                  type: integer
      responses:
        '200':
          description: Membresía creada o renovada exitosamente
    put:
      summary: Actualizar membresía
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tipo:
                  type: string
                fecha_inicio:
                  type: string
                fecha_fin:
                  type: string
      responses:
        '200':
          description: Membresía actualizada
